# Generated by Django 4.0.5 on 2022-06-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='status',
        ),
    ]
